            - name: Generate WordPress Archive
  # You may pin to the exact commit or the version.
  # uses: rudlinkon/action-wordpress-build-zip@dd36a9d3222ddbf914810918989a3c9de3ceb534
  uses: rudlinkon/action-wordpress-build-zip@1.3.0
  with:
    # How many days to keep the zip archive
    retention-days: # optional, default is 3
    # Do you want to install composer?
    install-composer: yes
          
